### ISSUE TITLE
CSS format can get messed up sometimes

### ISSUE THREAD

**Issue by trymbill** [NV/chrome-devtools-autosave#65]
Hi there,

I'm trying to incorporate devtools autosave in my workflow and I'm liking it a lot. One of the things I'm having a bit of an issue with is getting auto save to preserve the formatting of my CSS files. I might add some attributes and values to a clause and the outcome is sometimes like this:

```css
.class {
    overflow: hidden; 


height: 15px;
margin: 3px;

    background-color: #eff2f7;
    color: #000;
    cursor: default;
    }
```

My OCD goes nuts when I see this. Maybe this is a bug, I don't know, but shouldn't auto save just follow the indentation of the previous line?

Thanks.
